### ISSUE TITLE
Add support for SPAR (spontaneous argumentation)

### ISSUE THREAD

**Issue by rob-coco** [Ashwagandhae/debate-flow#7]
Devs,  I came across your app this morning when I was judging at a tournament, and I love it! Really well executed. I have a feature request - could you add support for SPAR as a format? Details here: https://argumentcenterededucation.com/wp-content/uploads/2016/10/SPARDebatesOverview16.010.01-2.pdf

**Comment by Ashwagandhae** [comment]
Thank you for the suggestion. I just implemented it, let me know if it looks good!

**Comment by rob-coco** [comment]
Thanks for making the update so fast - I realized that I linked to the wrong setup in my original comment. I've created a PR with the setup for NOF SPAR, which is what my kid and their school compete in. Let me know what you think. Either way - I've shared your app with the coaches at the school, they are stoked to use it with the students and judges!

**Comment by Ashwagandhae** [comment]
Merged, thank you for contributing. Also, thank you for sharing the app with others, let me know if there's anything else you'd like to see in the app!
